# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RottenFruit' do
pod 'AFNetworking', '~>1.3.1'
pod 'SVProgressHUD'
end

target 'RottenFruitTests' do

end

